### PR TITLE
Allow Sylius 1.11

### PR DESCRIPTION
**Pull request by adpeyre**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?   | no
| Fixed issue | #... 

Hi,

I'v tested this plugin on Sylius 1.11 and PHP 8.1. It works ;)
You can allow this Sylius version.

### CODE REVIEW

**Comment by adpeyre** [comment]
@oallain Can you merge it and create a tag ? I would like to use this plugin on my current project. :)

**Comment by oallain** [comment]
Can you add test in GitHub action? See https://github.com/synolia/SyliusGDPRPlugin/blob/master/.github/workflows/ci.yaml

**Comment by adpeyre** [comment]
Np @oallain Is it ok for you ?
Arf no, I need to adjust tests again.

**Comment by adpeyre** [comment]
@oallain Can you launch tests again ?

**Comment by adpeyre** [comment]
@oallain  I think, there is a problem with your tests (Phpstan or missing lib).

**Comment by GalloisLuca** [comment]
@adpeyre The problem doesn't come from our dev tools, the bundle [zend](https://github.com/zendframework/zend-stdlib) has been abandonned and replace by this one [laminas](https://github.com/laminas/laminas-stdlib/blob/3.8.x/src/PriorityQueue.php).

Can you in the file Synolia\SyliusGDPRPlugin\Processor\AdvancedActions\CompositeAdvancedActionsFormDataProcessor replace the use 

`use Zend\Stdlib\PriorityQueue;`

By

`use Laminas\Stdlib\PriorityQueue;`

Plz, i think it will work properly

**Comment by adpeyre** [comment]
@GalloisLuca Done ! ;)

**Comment by GalloisLuca** [comment]
@adpeyre I'm going to close this PR, i've open an [other one](https://github.com/synolia/SyliusGDPRPlugin/pull/36) with your commits to make this work with all versions.

Thank you for your contribution !

**Pull request closed without merging**
