### PR TITLE
Unknown routing

### PR DESCRIPTION
**Pull request by baiiko**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?   | no

Unknown route by default

### CODE REVIEW

**Comment by GalloisLuca** [comment]
Hello ! Thanks for the PR.
I'm not sure to understand your problem, what do you want to fix with that PR. I did try your branch on my local env and it doesn't fix anything unfortunatly :disappointed: . But if i understand, the BO can't work cause of a route name ? If so, i think you can fix it by adding the following configuration in your route file

```
sylius_gdpr_controllers:
    resource: '@SynoliaSyliusGDPRPlugin/Resources/config/routes/admin/gdpr.yaml'
    prefix: 'gdpr/'
    name_prefix: 'sylius_gdpr_'
```

**Comment by GalloisLuca** [comment]
It seems we made a mistake in the README. It says you should add

```
synolia_gdpr:
    resource: "@SynoliaSyliusGDPRPlugin/Resources/config/routes/admin/gdpr.yaml"
    prefix: '/%sylius_admin.path_name%'
```

But it can't work like that. You need to add the name prefix and prefix like in my last comment.
I'll make a PR about it ! :smile:

**Comment by baiiko** [comment]
> Hello ! Thanks for the PR. I'm not sure to understand your problem, what do you want to fix with that PR. I did try your branch on my local env and it doesn't fix anything unfortunatly disappointed . But if i understand, the BO can't work cause of a route name ? If so, i think you can fix it by adding the following configuration in your route file
> 
> ```
> sylius_gdpr_controllers:
>     resource: '@SynoliaSyliusGDPRPlugin/Resources/config/routes/admin/gdpr.yaml'
>     prefix: 'gdpr/'
>     name_prefix: 'sylius_gdpr_'
> ```

Hey, because your menu use : https://github.com/synolia/SyliusGDPRPlugin/blob/06c991419ba6019d5292cf0cc1653673d4829308/src/Menu/GDPRMenuListener.php

And this route does not exists :)

**Comment by oallain** [comment]
Hello @GuigZ- 
Thanks for your feedback.

@GalloisLuca has made another PR with fix [in plugin](https://github.com/synolia/SyliusGDPRPlugin/pull/41/files#diff-200cf3f0c4d5179b05f9568ef9bf16ad78080ccb3baf93b301eba824e82ae7ff) and [in Readme](https://github.com/synolia/SyliusGDPRPlugin/pull/41/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

I test it, and it works fine.
I close this one.

**Pull request closed without merging**
